// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuaLuuNiem.Data;

#nullable disable

namespace QuaLuuNiem.Migrations
{
    [DbContext(typeof(QuaLuuNiemContext))]
    partial class QuaLuuNiemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CTHDHoaDon", b =>
                {
                    b.Property<int>("CTHDsID")
                        .HasColumnType("int");

                    b.Property<int>("HoaDonsID")
                        .HasColumnType("int");

                    b.HasKey("CTHDsID", "HoaDonsID");

                    b.HasIndex("HoaDonsID");

                    b.ToTable("CTHDHoaDon");
                });

            modelBuilder.Entity("HoaDonThongTinKhachHang", b =>
                {
                    b.Property<int>("HoaDonsID")
                        .HasColumnType("int");

                    b.Property<int>("ThongTinKhachHangID")
                        .HasColumnType("int");

                    b.HasKey("HoaDonsID", "ThongTinKhachHangID");

                    b.HasIndex("ThongTinKhachHangID");

                    b.ToTable("HoaDonThongTinKhachHang");
                });

            modelBuilder.Entity("QuaLuuNiem.Model.CTHD", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("MaHD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CTHD", (string)null);
                });

            modelBuilder.Entity("QuaLuuNiem.Model.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaHD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBan")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("QuaLuuNiem.Model.SanPham", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThongTinGioHangID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ThongTinGioHangID");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("QuaLuuNiem.Model.ThongKeDoanhThu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ThongKeDoanhThu", (string)null);
                });

            modelBuilder.Entity("QuaLuuNiem.Model.ThongTinGioHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ThongTinGioHang", (string)null);
                });

            modelBuilder.Entity("QuaLuuNiem.Model.ThongTinKhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThongTinGioHangID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ThongTinGioHangID");

                    b.ToTable("ThongTinKhachHang", (string)null);
                });

            modelBuilder.Entity("CTHDHoaDon", b =>
                {
                    b.HasOne("QuaLuuNiem.Model.CTHD", null)
                        .WithMany()
                        .HasForeignKey("CTHDsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuaLuuNiem.Model.HoaDon", null)
                        .WithMany()
                        .HasForeignKey("HoaDonsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HoaDonThongTinKhachHang", b =>
                {
                    b.HasOne("QuaLuuNiem.Model.HoaDon", null)
                        .WithMany()
                        .HasForeignKey("HoaDonsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuaLuuNiem.Model.ThongTinKhachHang", null)
                        .WithMany()
                        .HasForeignKey("ThongTinKhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuaLuuNiem.Model.SanPham", b =>
                {
                    b.HasOne("QuaLuuNiem.Model.ThongTinGioHang", null)
                        .WithMany("SanPhams")
                        .HasForeignKey("ThongTinGioHangID");
                });

            modelBuilder.Entity("QuaLuuNiem.Model.ThongTinKhachHang", b =>
                {
                    b.HasOne("QuaLuuNiem.Model.ThongTinGioHang", null)
                        .WithMany("ThongTinKhachHangs")
                        .HasForeignKey("ThongTinGioHangID");
                });

            modelBuilder.Entity("QuaLuuNiem.Model.ThongTinGioHang", b =>
                {
                    b.Navigation("SanPhams");

                    b.Navigation("ThongTinKhachHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
